### ISSUE TITLE
Attributes branch_time*

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#195] opened 2017-06-26 11:13 UTC
Hi *,
when I use cmor 3.2.3 it writes branch_time attributes as strings:
`branch_time_in_child = "0.000"`
but according to the "CMIP6 Global Attributes, DRS, ... " document it should be double precision. CIM has marked testdata for that. Since I can only pass strings in the json file for `cmor_dataset` / `cmor_set_curr_dataset_att`, it needs to be changed in the cmor code, right?

Best regards and thank in advance,
Fabian

**Comment by taylor13** [comment] 2017-06-27 01:07
Yes, branch_time is a double precision variable attribute.  This looks like an error in CMOR3.

**Comment by dnadeau4** [comment] 2017-06-27 20:30
I reverted to the old 3.2.3 version and I could not reproduce this.

`:branch_time_in_child = 2310. ;`

I also tried to change the input to `string` which was converted to `double` 

Here is the code for "branch_time_something".  It converts the string to double...

https://github.com/PCMDI/cmor/blob/CMOR-3.2.3/Src/cmor.c#L2904-L2924

**Comment by dnadeau4** [comment] 2017-07-12 17:16
@wachsylon can we close this issue?

**Comment by dnadeau4** [comment] 2017-07-13 21:17
Actually 95 is ASCII character for `_`.  I am releasing 3.2.5 and will change this for `strncmp`.

What compiler are you using?

**Comment by dnadeau4** [comment] 2017-07-13 21:28
F

**Closed by dnadeau4** 2017-07-13 21:28 UTC
Labels: Can't reproduce
