### ISSUE TITLE
Error: frequency attribute not passed or blanked from cmip table (version 3.2.7)

### ISSUE THREAD

**Issue by KristianJS** [PCMDI/cmor#262] opened 2017-11-01 16:55 UTC
I am trying to use cmor3 on some test data from the EC-Earth model, and running into a problem which I don't understand:

---

C Traceback:
! In function: cmor_set_cur_dataset_attribute_internal
! called from: cmor_setGblAttr
! called from: cmor_write
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error:  Dataset error, required attribute frequency was not passed or blanked
!
!!!!!!!!!!!!!!!!!!!!!!!!!

---

and then shortly after

---

C Traceback:
! In function: _CV_checkGblAttributes
! called from: cmor_write
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Your Control Vocabulary file specifies one or more
! required attributes.  The following
! attribute was not properly set.
! 
! Please set attribute: "frequency" in your input file.
!
!!!!!!!!!!!!!!!!!!!!!!!!!

---

This is called when trying to cmorize with the CMIP6_CFday.json file, but from testing it seems to throw the same thing with other tables as well. This table does contain "frequency" : "day" in the header:

"Header": {
        "data_specs_version": "01.00.07",
        "table_id": "Table CFday",
        "realm": "atmos",
        "frequency": "day",
        "cmor_version": "3.2",
        "table_date": "22 April 2017",
        "missing_value": "1e20",
        "product": "model-output",
        "approx_interval": "1.00000",
        "generic_levels": "alevel alevhalf",
        "mip_era": "CMIP6",
        "Conventions": "CF-1.7 CMIP-6.0"

the CMIP6_CV.json file also contains frequency information. Does anyone know what the problem might be? How might the frequency attribute fail to be set in the variable?

**Comment by taylor13** [comment] 2017-11-01 18:25
I think the problem is that you are relying on release 1.00.07 from last April.  Try using the current release (1.00.17, I think), and that should fix your problem.  Let us know if you run into further problems.

**Comment by durack1** [comment] 2017-11-01 23:27
@KristianJS it would be best to update your CMOR tables to the latest, see https://github.com/PCMDI/cmip6-cmor-tables.

The `01.00.16` update was completed back on the 4th Octobe 2017, subsequent updates were undertaken to amend or add new model (source_id) registrations

**Comment by KristianJS** [comment] 2017-11-02 15:48
Oh, that's silly. I am trying to use the ece2cmor3 software, which has its own copies of the CMIP6 tables, but they were outdated! I have replaced them with the up to date ones now. Will let you know if I run into further problems.

**Comment by durack1** [comment] 2017-11-02 16:01
@KristianJS we'll close this issue for now, and reopen if further issues occur

**Closed by durack1** 2017-11-02 16:01 UTC
Labels: question
