### ISSUE TITLE
Issues when creating CFsubhr variables

### ISSUE THREAD

**Issue by lamaliang** [PCMDI/cmor#633] opened 2021-09-24 09:00 UTC
Hello 
Our cmor version is 3.5, when I create the file for CFsubhr there are some error message as following:
! In function: cmor_define_dimensions
!

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: NetCDF error (-54:NetCDF: NC_UNLIMITED size already in use) for dimension definition of
! axis:  (-1), for variable 2 (ps, table: CFsubhr)
!
!!!!!!!!!!!!!!!!!!!!!!!!!

My netcdf file format is NetCDF4-Classic and variable time is unlimited. I had try many methods to modify file, but the result is the same. How can I do? please

**Comment by durack1** [comment] 2021-09-24 19:29
Hi @lamaliang the [latest CMOR release is 3.6.1](https://github.com/PCMDI/cmor/releases/tag/3.6.1).

I suggest you update first, and see if the issue persists.

I will close this issue, please reopen if the problem is not resolved

**Closed by durack1** 2021-09-24 19:29 UTC
