### ISSUE TITLE
NAN and time coordinate

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#505] opened 2019-06-25 20:20 UTC
A user has posted the following:

-----
Hi,

I’m sending this to obs email because I’m using edited demo examples, let me know if I should submit this through git instead.

I’m running the examples for GPCP monthly and daily files, CMOR version 3.4.0 and Python 2.7.15. The cmor output files show all nan and missing values using cdo infon, although the values are identical with the input files using ncdump. Also, the input files show the usual cmor monthly times but the cmor output adds a half-month to the output times, which causes the months to look nonsequential (1,3,3,5,5,7,8 etc) (this I know how to fix if necessary).

Since the output data is retained I thought that I must have misconfigured something and it might be obvious to you where I should look to find the problem – at least with the nan issue. The demo file (REMSS-PRW) works as expected with cdo infon for both input, output and monthly time. I’ve compared the usual suspects – time units, variable units, fill value, etc. and don’t see any culprits.

thanks in advance for your help,

-----

I don't think we can address the "cdo infon" issue; it appears that ncdump correctly displays the data.

The time-coordinate issue might be caused by using a unit of "months since ...", which is forbidden in obs4MIPs and may not be handled correctly by CMOR.  Perhaps the user can let us know what units are used in the output files.

[note that a month is not a proper "unit", because it length varies from one month to the next.]

[Also note that for monthly mean data, CMOR will always define the coordinate values as the *middle* of a month (and the bounds will mark the beginning and end of each month).]

**Comment by jhz0** [comment] 2019-06-26 18:11
Thanks for your reply. The REMSS-PRW demo file is the one furnished in the obs4MIPs cmor demo files (rss_ssmi_prw_v06.6-demo.nc) -- it has months as the time dimension and units. My files have days since time units and were previously output by CMOR2.

I don't think time units are the issue, my concern is the nan and missing values in cdo (which has worked reliably with all my cmor2 files). I think the issue may be something like the NetCDF conversion. My main question is if anyone has seen incorrectly reported values in their output with cmor3/obs4MIPs sample script. I'll keep testing...

**Comment by durack1** [comment] 2019-06-26 18:56
@jhz0 CMOR uses the bounds attribute to assign the time axis. In the demo, we have to fix the bounds and you can see this is done [here](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/runCmorDemo.py#L25-L31). The `cmor.write` function then takes both inputs as arguments (see [here](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/runCmorDemo.py#L69))

**Comment by taylor13** [comment] 2019-06-26 22:00
I'm pinging @wachsylon who may have encountered this issue:  "cdo infon" appears to indicate all values are either "nan" or "missing", whereas ncdump indicates that all values are defined.

**Comment by jhz0** [comment] 2019-06-27 00:18
Thanks for the replies! I solved the issue by commenting out the cmor.set_variable_attributes valid_min and valid_max lines. Could these be added as warnings in the table instead of hard-wired in the file?

Still working on the correct output time units, the input file units are in days since 1900 and the monthly intervals are correct for a cmor file, but the output file is still incorrect; I'll keep testing.

Input:
`time = "1979-01-16 12", "1979-02-15", "1979-03-16 12", "1979-04-16", `

Output example:
` time = "1979-01-31 06", "1979-03-01 18", "1979-03-31 18", "1979-05-01 06", `

**Comment by durack1** [comment] 2019-06-27 00:20
@jhz0 you might want to check the time bounds, I think these are the culprit

@gleckler1 ping

**Comment by wachsylon** [comment] 2019-06-27 09:55
@jhz0 
I can check the `cdo info` issue and we should take it to the cdo forum.
Lets discuss this here: https://code.mpimet.mpg.de/boards/2/topics/7698

**Comment by jhz0** [comment] 2019-06-27 12:27
@wachsylon 
I was planning on a visit to the cdo forums but first want to better understand the necessity/requirement (from a cmor3 POV) and effect (on the NetCDF side) of adding the valid_min/max attribute. I'll work on this today -- thanks.

**Comment by jhz0** [comment] 2019-06-28 12:26
@wachsylon @taylor13 
It turns out I was using the demo file incorrectly, I hadn't either commented out the default values of valid_min/max or edited them to suit my data.

It looks to me as if cmor (and perhaps also cdo) are working as intended. I read through some related issues (i.e., https://github.com/PCMDI/cmor/issues/237) and better understand the concerns and uses of valid_min and valid_max. I'll now look closer at cdo's treatment of these attributes (and other utilities I use, the ones NetCDF docs refer to as 'conforming generic applications').

**Comment by durack1** [comment] 2019-06-28 19:13
@jhz0 great, thanks for following up here. If you believe your issue is resolved, please close this issue.

**Comment by jhz0** [comment] 2019-06-28 19:59
@durack1 Not sure I can close as a commenter, maybe @taylor13 should?

**Comment by durack1** [comment] 2019-06-28 20:00
@jhz0 good point, I had forgotten that @taylor13 opened this - I will close

**Closed by durack1** 2019-06-28 20:00 UTC
