### ISSUE TITLE
CMOR 3.2.7 Python doesn't support writing non-string attributes.

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/cmor#243] opened 2017-09-29 18:49 UTC
In relation to #237, the suggestion was to use cmor.set_variable_attribute to set valid_min and valid_max on the obs4MIPs output variable. These attributes must match the data type of the variable, but the CMOR 3.2.7 Python binding doesn't allow this. Per the CMOR documentation

> This function is unlikely to be called in preparing CMIP5 output, except to delete the “ext_cell_measures” attribute (setting it to a empty string). For this reason you can only set character type attributes at the moment via Python and Fortran.

**Comment by taylor13** [comment] 2017-09-29 21:27
ignore my last post, then on the other issue.  I guess it only works in C.

**Comment by durack1** [comment] 2017-10-03 23:50
@JimBiardCics @taylor13 this is a dupe of #244 (which has a better example) so will close this, and we can redirect discussion into #244

**Closed by durack1** 2017-10-03 23:50 UTC
