### ISSUE TITLE
vertices_longitude and vertices_latitude missing from the standard names list

### ISSUE THREAD

**Issue by piotrflorek** [PCMDI/cmor#273] opened 2017-12-04 10:14 UTC
In the CMOR-produced (v. 3.2.7) ocean files, `vertices_longitude` and `vertices_latitude` appear as the CF standard names (`vertices_longitude:standard_name = "vertices_longitude";` `vertices_latitude:standard_name = "vertices_latitude";`), although they are not present in the current (v.47) version of the table, nor they are mentioned in the CF Trac website or a proposal list.

**Comment by durack1** [comment] 2017-12-04 17:51
@piotrflorek these grid-related fields are included in the [PCMDI/cmip6-cmor-tables/Tables/CMIP6_grids.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_grids.json) file. These fields have been inherited from the CMIP5 data spec and have been pulled forward into CMIP6.

The latest version of the [PCMDI/cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables) aligns with the current [01.00.18 version](http://clipc-services.ceda.ac.uk/dreq/index.html) of the data request.

I'll close this issue, as I believe your query is answered, If not please continue to raise questions against this issue (reopen if needed)

@taylor13 @dnadeau4

**Comment by taylor13** [comment] 2017-12-04 18:06
I think the problem is that vertices_longitude is not a legal "standard name", so these files won't be CF-compliant.  
In CMIP5, there was no standard_name defined for these two variables, and there is no need for one in CMIP6 if these are "boundary" variables.  Are they boundary variables?

**Comment by taylor13** [comment] 2017-12-04 18:08
I looked in https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_grids.json and found the wrongly included standard_names for vertices_latitude and vertices_longitude, so there seems to be a problem with the CMOR tables.  [I think the "grid" table is added to the "data request" table by Denis because CMOR needs this grid information.

**Comment by matthew-mizielinski** [comment] 2017-12-05 09:09
Just to confirm the issue that @piotrflorek has raised; the latitude, longitude variables for variables processed by CMOR on our ocean grid (tripolar) are of the form

        float latitude(j, i) ;
                latitude:standard_name = "latitude" ;
                latitude:units = "degrees_north" ;
                latitude:missing_value = 1.e+20f ;
                latitude:_FillValue = 1.e+20f ;
                latitude:bounds = "vertices_latitude" ;
        ...
        float vertices_latitude(j, i, vertices) ;
                vertices_latitude:standard_name = "vertices_latitude" ;
                vertices_latitude:units = "degrees_north" ;
                vertices_latitude:missing_value = 1.e+20f ;
                vertices_latitude:_FillValue = 1.e+20f ;

the `vertices_latitude` variable has an invalid standard name. The `vertices_latitude` and `vertices_longitude` describe the corners of the grid cells, i.e. the boundaries, on the ocean grid. 

@taylor13, if you are happy for the standard_name to be removed this would be by far the simplest fix. I note that in our standard atmosphere grid the bounds variables attached to the `lat` and `lon` coordinate variables have no attributes.

**Comment by dnadeau4** [comment] 2017-12-05 17:55
I can change the `standard name` for these 2 grid variables.  Any idea what they should be set too?  I guess the name `vertices_lattitude` was just copied in the standard name.

**Comment by taylor13** [comment] 2017-12-06 18:04
I'm not sure how the CMIP6_grids.json file got generated.  In CMIP5 the standard_name attribute was *not* included for "vertices_latitude" and "vertices_longitude" in the Tables_CMIP5_grids file, and I presume It wasn't included in the output files either.  This is what we want also for CMIP6.  As noted above the bounds (and vertices) for coordinate variables do not need (and in this case shouldn't have) standard_name attributes.  Will eliminating the standard_name for these two variables break anything?

**Comment by dnadeau4** [comment] 2017-12-06 22:52
No it will not,  I can just remove them from the tables.

**Comment by dnadeau4** [comment] 2017-12-13 22:09
Fix in 3.3.0

**Closed by dnadeau4** 2017-12-13 22:09 UTC

**Comment by wachsylon** [comment] 2018-03-20 17:33
Hi,
when producing variables on such a grid now (tested for CMOR 3.2.8 and 3.3.1), we do not have 'standard_name' attributes for latitude and longitude anymore:
```
        float latitude(j, i) ;
		latitude:units = "degrees_north" ;
		latitude:missing_value = 1.e+20f ;
		latitude:_FillValue = 1.e+20f ;
		latitude:bounds = "vertices_latitude" ;
	float vertices_latitude(j, i, vertices) ;
		vertices_latitude:units = "degrees_north" ;
		vertices_latitude:missing_value = 1.e+20f ;
		vertices_latitude:_FillValue = 1.e+20f ;
```
Can you reproduce this?
Additionally, our QA annotates that CF recommends not assigning _FillValue and missing_value to the vertices coordinate variables. Do you agree?
Thanks and best regards,
Fabi

**Comment by wachsylon** [comment] 2018-03-20 17:42
Also, for variables "areacello" and "deptho" in CMIP6_Ofx.json
an unused dimension <bnds> is in the output file.

**Comment by durack1** [comment] 2018-03-20 17:45
@wachsylon can you provide an `ncdump -h` output for the `areacello` and `deptho` files - this will fast track ascertaining what's gone wrong here - same as above (and inline comment) would be great

**Comment by wachsylon** [comment] 2018-03-20 17:58
Of course,
```
netcdf areacello_Ofx_MPI-ESM-1-2-HR_historical_r1i1p1f1_gn {
dimensions:
	j = 404 ;
	i = 802 ;
	bnds = 2 ;
	vertices = 4 ;
variables:
	int j(j) ;
		j:units = "1" ;
		j:long_name = "cell index along second dimension" ;
	int i(i) ;
		i:units = "1" ;
		i:long_name = "cell index along first dimension" ;
	float latitude(j, i) ;
		latitude:units = "degrees_north" ;
		latitude:missing_value = 1.e+20f ;
		latitude:_FillValue = 1.e+20f ;
		latitude:bounds = "vertices_latitude" ;
	float longitude(j, i) ;
		longitude:units = "degrees_east" ;
		longitude:missing_value = 1.e+20f ;
		longitude:_FillValue = 1.e+20f ;
		longitude:bounds = "vertices_longitude" ;
	float vertices_latitude(j, i, vertices) ;
		vertices_latitude:units = "degrees_north" ;
		vertices_latitude:missing_value = 1.e+20f ;
		vertices_latitude:_FillValue = 1.e+20f ;
	float vertices_longitude(j, i, vertices) ;
		vertices_longitude:units = "degrees_east" ;
		vertices_longitude:missing_value = 1.e+20f ;
		vertices_longitude:_FillValue = 1.e+20f ;
	float areacello(j, i) ;
		areacello:standard_name = "cell_area" ;
		areacello:long_name = "Grid-Cell Area" ;
		areacello:comment = "Horizontal area of ocean grid cells" ;
		areacello:units = "m2" ;
		areacello:original_name = "areacello" ;
		areacello:cell_methods = "area: sum" ;
		areacello:history = "2018-03-19T18:53:11Z altered by CMOR: replaced missing value flag (-9e+33) with standard missing value (1e+20)." ;
		areacello:missing_value = 1.e+20f ;
		areacello:_FillValue = 1.e+20f ;
		areacello:coordinates = "latitude longitude" ;

```
and

```
netcdf deptho_Ofx_MPI-ESM-1-2-HR_historical_r1i1p1f1_gn {
dimensions:
	j = 404 ;
	i = 802 ;
	bnds = 2 ;
	vertices = 4 ;
variables:
	int j(j) ;
		j:units = "1" ;
		j:long_name = "cell index along second dimension" ;
	int i(i) ;
		i:units = "1" ;
		i:long_name = "cell index along first dimension" ;
	float latitude(j, i) ;
		latitude:units = "degrees_north" ;
		latitude:missing_value = 1.e+20f ;
		latitude:_FillValue = 1.e+20f ;
		latitude:bounds = "vertices_latitude" ;
	float longitude(j, i) ;
		longitude:units = "degrees_east" ;
		longitude:missing_value = 1.e+20f ;
		longitude:_FillValue = 1.e+20f ;
		longitude:bounds = "vertices_longitude" ;
	float vertices_latitude(j, i, vertices) ;
		vertices_latitude:units = "degrees_north" ;
		vertices_latitude:missing_value = 1.e+20f ;
		vertices_latitude:_FillValue = 1.e+20f ;
	float vertices_longitude(j, i, vertices) ;
		vertices_longitude:units = "degrees_east" ;
		vertices_longitude:missing_value = 1.e+20f ;
		vertices_longitude:_FillValue = 1.e+20f ;
	float deptho(j, i) ;
		deptho:standard_name = "sea_floor_depth_below_geoid" ;
		deptho:long_name = "Sea Floor Depth Below Geoid" ;
		deptho:comment = "Ocean bathymetry.   Reported here is the sea floor depth for present day relative to z=0 geoid. Reported as missing for land grid cells." ;
		deptho:units = "m" ;
		deptho:original_name = "depto" ;
		deptho:cell_methods = "area: mean" ;
		deptho:cell_measures = "area: areacello" ;
		deptho:history = "2018-03-19T18:53:09Z altered by CMOR: replaced missing value flag (-9e+33) with standard missing value (1e+20)." ;
		deptho:missing_value = 1.e+20f ;
		deptho:_FillValue = 1.e+20f ;
		deptho:coordinates = "latitude longitude" ;

```

**Comment by wachsylon** [comment] 2018-04-26 15:02
This `missing_value` and `_FillValue` as well as the missing `standard_name` occur for many variables in Oclim Ofx, Omon, Oyr, SImon. @durack1 @dnadeau4

**Comment by durack1** [comment] 2018-04-26 16:32
@wachsylon are you referring to the coordinates, rather than the variables (e.g. `deptho` above, which does include `standard_name`, and `_FillValue` along with other correct attributes)? For the `longitude` coordinate, the defined coordinate does in fact contain all this information - see [CMIP6_coordinate.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L777-L798)

**Comment by taylor13** [comment] 2018-04-26 18:32
I wouldn't place a high priority on removing "bnds" from the file.  Although it isn't needed, it isn't hurting anything is it?

latitude and longitude should have standard_name included (but vertices_latitude and vertices_longitude don't need standard_name).

I don't think missing_value and _FillValue should be defined for the coordinates and their vertices, but I don't think it is essential to remove them.

I think all of the above problems appear only in files with grids that are not latxlon.  Is this true?

**Comment by wachsylon** [comment] 2018-05-15 15:49
@taylor13 Yes and I agree with all your points.

**Comment by liu-ran** [comment] 2024-01-02 14:50
hi, how to use the vertices_longitude and vertices_latitude to regrid the ocean u,v from the tripolar grid into regular lat-lon grid?

**Comment by taylor13** [comment] 2024-01-02 19:29
That is a good question, but this is not really the place to discuss that issue because CMOR does no regridding.  There are several software packages available that require the user to provide the longitude and latitude vertices and will then calculate the "weights" needed to regrid the data.  A recent discussion of conservative remapping can be found [here](https://gmd.copernicus.org/preprints/gmd-2023-177/gmd-2023-177.pdf), and it references several popular regridding packages.

**Comment by durack1** [comment] 2024-01-02 20:40
I just peeked at https://github.com/PCMDI/cmip6-cmor-tables/blob/main/Tables/CMIP6_grids.json#L137-L155 and noted that both *_vertices have a blank standard_name entry, so this is right to be closed.

@liu-ran as @taylor13 notes above, there are a number of software packages that can regrid output, I suggest you redirect your query to one of these
