### ISSUE TITLE
Differences between variable name and out_name

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#246] opened 2017-10-04 12:55 UTC
In the `01.00.15` version of the MIP tables, there are a number of variables that have an `out_name` that differs from the variable name, but the variable `out_name` already exists in the MIP table. See, for example, [ua in CMIP6_6hrPlevPt.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_6hrPlevPt.json#L484) and [ua7h in CMIP6_6hrPlevPt.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_6hrPlevPt.json#L502), which has an `out_name` of `ua`.

This means, once `cmor.setup` and `cmor.dataset_json` have been run, if someone tries to produce `ua` from `6hrPlevPt`, then `ua7h` from `6hrPlevPt`, wouldn't the corresponding filename of the output netCDF file be the same? Wouldn't this cause issues?

**Comment by ehogan** [comment] 2017-10-04 12:59
cc @martinjuckes @taylor13 @dnadeau4

**Comment by dnadeau4** [comment] 2017-10-04 16:46
Yes the filename will be exactly the same and one file will be clobbered. 
My guess is that data provider will select which levels the want
https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L1603
https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L1648

**Comment by durack1** [comment] 2017-10-04 17:37
@ehogan will there be a real world example that both of these variables (with different height axes) will be written at the same time?

@taylor13 if the answer to the above is yes, then we need to determine how to deal with this, as both files will share the same filename and DRS (they originate from the same table)

**Comment by ehogan** [comment] 2017-10-05 11:03
@durack1 I don't currently have a real world example that demostrates this issue. Perhaps a better question would have been "What is the reasoning behind using an `out_name` that is different to the variable name?"

**Comment by taylor13** [comment] 2017-10-05 12:38
The table "entry" (name) can distinguish between two variables appearing in the CMOR table that have different attribute values.  Since the requested pressure levels are different between ua and ua7h, they have different table "entries".  For a given experiment, they shouldn't both be requested.  In particular if ua7h is needed that will already include ua (which only has 3 pressure levels requested (assuming the 3 are included in the 7 levels of ua7h).  So there is no danger that two files will be produced with the same name.
In CMIP5 we didn't have a case where variables were requested in different number of levels, but we did have cases where a field might be time dependent in one model but time-invariant in another.  We had two different entries (but the same output name) for the variable, but the user was supposed to choose one or the other and not report both.

**Comment by durack1** [comment] 2017-10-05 15:05
@ehogan if you are satisfied with the answer of @taylor13 above, can this issue be closed?

**Comment by matthew-mizielinski** [comment] 2017-10-06 11:29
@ehogan and I have discussed this, and I think this may come back to how "choices" are defined in the data request and then carried through into CMOR.

The variables referred to above, `ua` and `ua7h`, both appear in the `6hrPlevPt` table in the data request for the following experiments;
 * CMIP: 
   * amip
   * historical, historical-ext, esm-hist, esm-hist-ext
   * piControl, esm-piControl
  * HighResMIP
    * All (I think).

From the [amip spreadsheet](http://clipc-services.ceda.ac.uk/dreq/data/tabs02/cmvme_TOTAL_amip_3_3.xlsx) from the data request you'll see that both variables appear in the 6hrPlevPt sheet; `ua` requested by CMIP, DAMIP, HighResMIP, Volmip and `ua7h` by CORDEX and HighResMIP.

From the HighResMIP perspective I understand that the intention was for groups to provide the 3 pressure levels as first priority, but include the extra 4 if possible, i.e. there should be an element of choice to produce `ua` __or__ `ua7h`. I believe that Malcolm Roberts and Martin discussed this some time ago and that having two entries in the relevant mip table was the resulting solution.

The data request does have some "choice" elements (look for the [varChoiceLinkR section](http://clipc-services.ceda.ac.uk/dreq/index/varChoiceLinkR.html)), but it isn't 100% clear how to "make" these choices. This is an extra layer of detail that we haven't necessarily accounted for in our preparations for CMIP6 -- it isn't too complex to deal with given how limited the extent of the issue is (69 variables), but (like the information on scientific objectives) it isn't something we have been taking into account.

I think all that is needed is some clear and easy to find documentation of what choices there are to be made and how to make them in an informed way.

**Comment by taylor13** [comment] 2017-10-06 23:12
@matthew-mizielinski @ehogan I think this is an issue that should be raised with the data request an Martin Juckes.  Do you agree?  Is there also something in CMOR that needs revision?

**Comment by matthew-mizielinski** [comment] 2017-10-09 08:40
I agree, this is probably better understood and dealt with within the framework of the data request. 

I've raised this at cmip6dr/Request#61 to cover the data request aspect.

**Comment by ehogan** [comment] 2017-10-09 16:36
I just tried producing `ua` and `ua7h` at the same time, using the default settings for `cmor_setup` (specifically `netcdf_file_action=CMOR_PRESERVE`, see https://cmor.llnl.gov/mydoc_cmor3_api/#cmor_setup for more details). However, CMOR does not exit like the documentation says, due to the changes I made in #171. The first error message I see is:

```
! Error: Output file ( CMIP6/CMIP6/CMIP/MOHC/UKESM1-0-LL/amip/r1i1p1f1/6hrPlevPt/ua/gn/v20171009/ua_6hrPlevPt_UKESM1-0-LL_amip_r1i1p1f1_gn_201001010600-201001010600.nc ) already exists,
! remove file or use CMOR_REPLACE or
! CMOR_APPEND for CMOR_NETCDF_MODE value
! in cmor_setup for convenience the file
! you were trying to write has been saved
! at: CMIP6/CMIP6/CMIP/MOHC/UKESM1-0-LL/amip/r1i1p1f1/6hrPlevPt/ua/gn/v20171009/ua_6hrPlevPt_UKESM1-0-LL_amip_r1i1p1f1_gn_201001010600-201001010600.nc.copy
```

followed by

```
! Error: could not rename temporary file: CMIP6/CMIP6/CMIP/MOHC/UKESM1-0-LL/amip/r1i1p1f1/6hrPlevPt/ua/gn/v20171009/ua_6hrPlevPt_UKESM1-0-LL_amip_r1i1p1f1_gnKDxRiq15995.nc to final file
name: CMIP6/CMIP6/CMIP/MOHC/UKESM1-0-LL/amip/r1i1p1f1/6hrPlevPt/ua/gn/v20171009/ua_6hrPlevPt_UKESM1-0-LL_amip_r1i1p1f1_gn_201001010600-201001010600.nc
```

The second error occurs because the rename that occurred as described in the first error message did not rename the finalise file, but the temporary file. I've submitted a pull request to deal with this (#249). Would it be possible for you to update the [documentation](https://cmor.llnl.gov/mydoc_cmor3_api/#cmor_setup) to say something about the fact that the file is copied rather than `in which case the program will error exit`? :)

**Comment by taylor13** [comment] 2017-10-10 09:09
I think you are trying to do something that we don't want you to do: write both ua and ua7h.  ua is redundant because ua7h already includes the ua field.  Therefore, to avoid the error, simply stop trying to write "ua' when you've already written (or are planning to write) ua7h.  Then you won't encounter the problem.  I don't think there is any reason to  rename any files produced by CMOR.  Do you disagree?

**Comment by ehogan** [comment] 2017-10-13 13:39
The same issue will occur if `netcdf_file_action=CMOR_PRESERVE` is set and a user tries to reproduce `ua` (using a second call to CMOR); the pull request will handle this more appropriately. However, if you'd prefer that CMOR simply exit rather than perform the copy I could update the pull request accordingly?

**Comment by dnadeau4** [comment] 2017-12-13 22:26
@taylor13 Can you follow up on this?

**Comment by taylor13** [comment] 2018-01-31 22:35
After discussing with Denis, we agree that your suggested changes would be good (if they don't break any of the tests cases).
thanks.

**Comment by ehogan** [comment] 2018-02-01 16:19
Great, thanks for letting me know :)

**Comment by taylor13** [comment] 2018-02-06 21:18
If we implement this change, will we be asking for trouble in connection with the "version" issue https://github.com/PCMDI/cmor/issues/210 and https://github.com/PCMDI/cmor/issues/267 ?  Will discuss this with @dnadeau4  tomorrow, but @ehogan if you have any thing you want to say, please do.

**Comment by dnadeau4** [comment] 2018-02-14 19:50
@ehogan I merged your pull request, if you have problem with this let me know.  I did not create a test for it either.

**Closed by dnadeau4** 2018-02-14 19:50 UTC
Labels: question

**Comment by senesis** [comment] 2018-06-14 11:35
In the [DR issue referenced above](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/336), the problem is presented in a CMOR-agnostic way, as the issue is rather due to combination of DR content and CMIP6 output formating guidelines. No PR merge will fix the issue for those centers which do not use CMOR
