### ISSUE TITLE
time axis error

### ISSUE THREAD

**Issue by tsigarid** [PCMDI/cmor#43] opened 2015-09-10 18:29 UTC
I have a weird error, which I can’t tell whether it is a bug on my site or on CMOR’s side. The problem occurs in version 2.9.1 but does not in version 2.8.3, and it only occurs when writing 3d fields. The error I get is this:

! Error: axis time (table: 3D-M) has overlapping bounds values : 57701.000000, 57729.000000, 57701.000000 at index: 0 !

Of course, I use the same time values for all variables for the same month, and it does not occur in the 2d variables I save. In addition, in case it matters, it occurs when calling cmor_write during February (365 day calendar, so 28 days) and on the second 3d variable in a loop. 

I hope I explained it correctly. I can easily reproduce it, so if you want me to run any test and print any output for you, I’ll be more than happy to. Again, it happens in 2.9.1, but not in 2.8.3.

**Comment by dnadeau4** [comment] 2015-09-10 18:42
Can you provide me with at test.  That will be helpful and I can try to fix it quickly.

**Comment by tsigarid** [comment] 2015-09-10 18:44
I can try to create a short version of the code, but don’t you need my input files as well?

**Comment by doutriaux1** [comment] 2015-09-10 20:44
@tsigarid please can you simply copy/paste your axes values and bounds? That should be a good starting point for us, as well as the CMOR Tables name of the var you're trying to write (in the order you're writing them).

**Comment by tsigarid** [comment] 2015-09-12 18:53
The order I am writing is irrelevant. When I only convert temp, it works. When I only convert hus, it works. When I convert both in the same loop, it crashes on the second variable with 2.9.1, and it does not matter whether I do temp,hus, or hus,temp.

These are my bounds:
 Now converting JAN 2000
           1   15.5000000000000       0.000000000000000E+000   31.0000000000000
 Now converting FEB 2000
           2   45.0000000000000        31.0000000000000   59.0000000000000
 Now converting MAR 2000
           3   74.5000000000000        59.0000000000000   90.0000000000000
 Now converting APR 2000
           4   105.000000000000        90.0000000000000   120.000000000000
 Now converting MAY 2000
           5   135.500000000000        120.000000000000   151.000000000000
 Now converting JUN 2000
           6   166.000000000000        151.000000000000   181.000000000000
 Now converting JUL 2000
           7   196.500000000000        181.000000000000   212.000000000000
 Now converting AUG 2000
           8   227.500000000000        212.000000000000   243.000000000000
 Now converting SEP 2000
           9   258.000000000000        243.000000000000   273.000000000000
 Now converting OCT 2000
          10   288.500000000000        273.000000000000   304.000000000000
 Now converting NOV 2000
          11   319.000000000000        304.000000000000   334.000000000000
 Now converting DEC 2000
          12   349.500000000000        334.000000000000   365.000000000000

The first number is the month count, the second the mid-point in units of days (time variable), and the other two are the bounds (time_bnds(2,12)). When I try to convert two (or more) variables month 1 works, month 2 crashes on the second variable:

 Now converting JAN 2000
           1   15.5000000000000       0.000000000000000E+000   31.0000000000000
 Now converting FEB 2000
           2   45.0000000000000        31.0000000000000   59.0000000000000

C Traceback:
In function: cmor_check_monotonic
called from: cmor_write_var_to_file
called from: cmor_write


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                                                                     !
! Error: axis time (table: 3D-M) has overlapping bounds values : 54781.000000, 54809.000000, 54781.000000 at index: 0 !
!                                                                                                                     !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by tsigarid** [comment] 2015-09-12 18:54
PS: I only have this problem in 3d variables.

**Comment by dnadeau4** [comment] 2015-09-27 20:25
Your time axis is wrong, it has the same date twice.  54781.0

**Comment by tsigarid** [comment] 2015-09-28 15:16
Right, but this is a CMOR issue, since my time input is not repeated, as you can see in my diagnostic output. Plus, it only happens in 3D variables, and I use the exact same axes values for the 2D variables. Plus plus, it only happens in the last CMOR, not an older version.

**Comment by BeatriceCNRM** [comment] 2016-01-20 11:43
Hello,
I encountered exactly tsigarid's problem. Do you have any ideas of how to fix it?
Thanks

**Comment by dnadeau4** [comment] 2016-01-20 19:46
@BeatriceCNRM @tsigarid 
Looking at your diagnostic carefully,  the problem is in the time_bounds variable just before you call cmor_write.  This is the bounds you have:

* index 1: 54781.000000, 54809.000000
* index2:  54781.000000, ...

cmor is complaining that you time boundaries are not monotonic.    If you were able to write the first variable correctly and the failure happened on the second variable, it means that your time_bounds were not initialized properly the second time in your loop for some reason.  

Can you print your variables "time_bounds" just before your call cmor_write to make sure that it is properly setup.  cmor seems also to change your time units so you might want to print "time" as well and make sure the values are within boundaries the same way you did in your diagnostics.

I am not sure why it would only happens in 3D variables and why this would happens in 2.9.1.  @doutriaux1 would need to take a look what has changed in cmor since the last released in 2014. 

Is there a way I can look at your program?  I am sure I could find where is the problem very quickly.

**Comment by BeatriceCNRM** [comment] 2016-01-20 20:22
Hi Denis,

Thank you for your prompt answer !
I'm writing from France so I'm home now and don't have my programs.
Tomorrow morning I'll send you an e-mail with programs and much more
details. (I already checked the variables just before calling the routine,
they are ok).
Is it ok for you?
Thanks in advance

Beatrice

PS : your name sounds french.. Maybe we could communicate in french ;-)?

Le 20 janv. 2016 à 20:47, Denis Nadeau <notifications@github.com> a écrit :

@BeatriceCNRM <https://github.com/BeatriceCNRM> @tsigarid
<https://github.com/tsigarid>
Looking at your diagnostic carefully, the problem is in the time_bounds
variable just before you call cmor_write. This is the bounds you have:

   - index 1: 54781.000000, 54809.000000
   - index2: 54781.000000, ...

cmor is complaining that you time boundaries are not monotonic. If you were
able to write the first variable correctly and the failure happened on the
second variable, it means that your time_bounds were not initialized
properly the second time in your loop for some reason.

Can you print your variables "time_bounds" just before your call cmor_write
to make sure that it is properly setup. cmor seems also to change your time
units so you might want to print "time" as well and make sure the values
are within boundaries the same way you did in your diagnostics.

I am not sure why it would only happens in 3D variables and why this would
happens in 2.9.1. @doutriaux1 <https://github.com/doutriaux1> would need to
take a look what has changed in cmor since the last released in 2014.

Is there a way I can look at your program? I am sure I could find where is
the problem very quickly.

—
Reply to this email directly or view it on GitHub
<https://github.com/PCMDI/cmor/issues/43#issuecomment-173338062>.

**Comment by dnadeau4** [comment] 2016-01-20 20:58
@BeatriceCNRM I will wait for your email with the program tomorrow.  

BTW, I am French Canadian, but it is better to keep writing in English so more people can understand the issue and how we solved it.  ;-)
Regards,

**Comment by BeatriceCNRM** [comment] 2016-01-21 11:34
Hello Denis 

Here is the program I'm currently working on. 
You will see I added some print to check that the time values entering cmor_write are OK. They are, with: 

time= 47495.000000000000 
bnds_time= 47481.000000000000 47509.000000000000 

The diagnostic is the following one : 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
! ! 
! Error: axis time (table: monthly) has overlapping bounds values : 47481.000000, 47509.000000, 47481.000000 at index: 0 ! 
! ! 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
NB : 
1) It happens at the 2d call of the cmor_write (I indeed call it first for the 3D variable, and secondly to add the surface pressure in the file) 
2) It happens at the 2d step of the big loop over 3D variables (m=1,n3d) . If I for instance decide to output only the 'vmrch4' variable (m=6,6), it works. 
m=7,7 works too. But the loop m=6,7 does not... 
3) The same program worked with an older version of CMOR, in 2011. This version is at the moment no more available on my PC, so I could not check if my program still works with this older version, but nothing was changed in the program. 

Thank you very much for your help. Don't hesitate to ask for more details... 

Regards 

Beatrice 

----- Météo-France ----- 
JOSSE BEATRICE 
CNRM/GMGEC/CARMA 
beatrice.josse@meteo.fr 
Fixe : +33 561079372

**Comment by doutriaux1** [comment] 2016-01-21 15:50
@dnadeau4 or @BeatriceCNRM do you mind posting the actual code here? The attachment didn't make it to github.

**Comment by dnadeau4** [comment] 2016-02-02 01:51
@BeatriceCNRM
 We never got your code,  can you post it in attachment or send ti to my email: nadeau1@llnl.gov.  Thanks!

**Comment by dnadeau4** [comment] 2016-09-07 23:29
Need to revisit this.  Never found the problem.

**Comment by dnadeau4** [comment] 2016-11-23 21:23
@BeatriceCNRM Can you give this another try?  We updated CMOR so much that he problem might be solved.

**Comment by dnadeau4** [comment] 2017-03-03 03:16
@BeatriceCNRM Did you ever get around this issue?  I have not figured out what was the final problem.

**Comment by dnadeau4** [comment] 2017-04-19 22:06
@BeatriceCNRM Beatrice Feel free to re-open if this is still an issue.

**Closed by dnadeau4** 2017-04-19 22:06 UTC
Labels: question
